"""Figure.md §2 — discover inputs, print shape/columns/dtypes/head/categorical levels,
write figures/DATA_MANIFEST.md with the SHA-256 of every input file."""
import hashlib
import os
import sys

import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import data as D
from style import FIG_DIR

CATEG = ["alignment", "alignment_target", "n", "n_gw", "n_od", "treatment", "menu", "variant",
         "fd_multiplier", "B", "source"]


def sha256(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def main():
    out = ["# DATA_MANIFEST", "",
           "Generated by `plots/discover.py`. Every figure reads only the files below; SHA-256 "
           "recorded at discovery time.", ""]
    for code, (desc, paths) in D.FILES.items():
        out.append("## %s — %s" % (code, desc))
        if not paths:
            out.append("**NOT FOUND**")
            print(code, "NOT FOUND")
            continue
        for p in paths:
            ok = os.path.exists(p)
            out.append("- `%s`  " % os.path.relpath(p, D.ROOT))
            if not ok:
                out.append("  **MISSING FILE**")
                print(code, "MISSING", p)
                continue
            out.append("  sha256 `%s`" % sha256(p))
            if p.endswith(".csv"):
                df = pd.read_csv(p)
                out.append("  rows %d · columns: %s" % (len(df), ", ".join(
                    "`%s`:%s" % (c, str(t)) for c, t in df.dtypes.items())))
                for c in CATEG:
                    if c in df.columns and df[c].nunique() <= 30:
                        out.append("  levels `%s`: %s" % (c, sorted(df[c].dropna().unique().tolist())))
                print("%-4s %-60s rows=%d cols=%d" % (code, os.path.basename(p), len(df), df.shape[1]))
                print("     columns:", list(df.columns))
                print(df.head(3).to_string(max_cols=12, max_colwidth=14))
            else:
                print("%-4s %s" % (code, os.path.basename(p)))
        out.append("")
    out += [
        "## Derived mappings and notes", "",
        "- **FD rate per instance (§3.3, FIG 8a, tick labels):** D1 has no `fd_rate` column. "
        "D3 menu `B3` is the identical JOINT allocation on the identical 1,500 instances "
        "(check X1 in `Report_RQ_All.md`: max |C_B3 − C_JOINT| = 1.1e-13 on 1,500/1,500), so "
        "`fd_rate` is read from D3 rows with `menu == 'B3'`.",
        "- **t_B (FIG 2):** D5 has no separate WDP time; `t_B` is read from D3 (`menu == 'B3'`, "
        "same instance key) — the base WDP solve of the same instance, measured in the RQ2 run.",
        "- **t_C naive / accel (FIG 2–3):** D5 `t_C_naive` / `t_C_accel` = one base solve plus one "
        "removal solve per winner (RQ4 definition, MASTER §13); `t_kstar` = frontier construction.",
        "- **FIG 4 (label rule):** D9 JSON holds, per instance, the median and IQR of the speed-up "
        "over repeated runs (raw per-repeat timings were not stored). For B=3, instance n10 s999 "
        "uses the N=20 rerun (`timing_medians_B3_seeds999.json`), as in MASTER. Strip of raw "
        "repeats therefore not drawn. `ALL` = total-time ratio over the five instances "
        "(labelled 'pooled').",
        "- **Pool per driver class (FIG 1):** not present in D3 or D5 (only total pool per instance) "
        "— see MISSING.md.",
    ]
    os.makedirs(FIG_DIR, exist_ok=True)
    with open(os.path.join(FIG_DIR, "DATA_MANIFEST.md"), "w", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")
    print("\n-> figures/DATA_MANIFEST.md")


if __name__ == "__main__":
    main()
